---
- name: Listen for events on webhook
  hosts: web
  source:
    - ansible.eda.url_check:
        urls:
          - www.google.com
        delay: 15

  rules:
    - name: website is up
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: "Stat test 2"
          organization: BI-IT-AUTOMATION-INFIAC

    - name: website is down
      condition: event.url_check.status == "down"
      action:
        run_playbook:
          name: site_down.yml
